-- Import correspondence emails from CSV data
UPDATE public.clients SET correspondence_emails = ARRAY['josh@theemailagency.com'] WHERE client_code = 'TEA';
UPDATE public.clients SET correspondence_emails = ARRAY['support@semanticlinks.io', 'bradley@semanticlinks.io', 'wayne@semanticlinks.net'] WHERE client_code = 'SEM';
UPDATE public.clients SET correspondence_emails = ARRAY['lou@basimatony.com'] WHERE client_code = 'BST';
UPDATE public.clients SET correspondence_emails = ARRAY['jandre@v8media.co.za', 'luca@v8media.co.za'] WHERE client_code = 'V8';
UPDATE public.clients SET correspondence_emails = ARRAY['oli@mabanemedia.com', 'ross@mabanemedia.com'] WHERE client_code = 'MBM-sales';
UPDATE public.clients SET correspondence_emails = ARRAY['vineesh@almcorp.com'] WHERE client_code = 'ALM';
UPDATE public.clients SET correspondence_emails = ARRAY['james@theecomagency.co.uk'] WHERE client_code = 'ECA';
UPDATE public.clients SET correspondence_emails = ARRAY['pathik@integratedwebworks.com'] WHERE client_code = 'INT';
UPDATE public.clients SET correspondence_emails = ARRAY['jeremy@noetzelman.com'] WHERE client_code = 'PRS';
UPDATE public.clients SET correspondence_emails = ARRAY['atishay@eagleinfoservices.com'] WHERE client_code = 'HYPERKE';
UPDATE public.clients SET correspondence_emails = ARRAY['manuel@amz-ads.com'] WHERE client_code = 'AMZ';
UPDATE public.clients SET correspondence_emails = ARRAY['victor@pdmutah.com'] WHERE client_code = 'PDM';
UPDATE public.clients SET correspondence_emails = ARRAY['sduverseau@smartpandalabs.com'] WHERE client_code = 'SPLABS';
UPDATE public.clients SET correspondence_emails = ARRAY['evan@galaxyseo.com', 'jonathan@galaxyseo.com'] WHERE client_code = 'GS';
UPDATE public.clients SET correspondence_emails = ARRAY['clemaire@traktekpartners.com', 'jphillips@traktekpartners.com'] WHERE client_code = 'TTK';
UPDATE public.clients SET correspondence_emails = ARRAY['nableatherco@gmail.com'] WHERE client_code = 'NAB';
UPDATE public.clients SET correspondence_emails = ARRAY['tom@csmagency.ie'] WHERE client_code = 'ATK';
UPDATE public.clients SET correspondence_emails = ARRAY['adam@makeitefficient.com', 'mike@makeitefficient.com'] WHERE client_code = 'EM';
UPDATE public.clients SET correspondence_emails = ARRAY['chris@hirehawk.com'] WHERE client_code = 'HHK';
UPDATE public.clients SET correspondence_emails = ARRAY['robert@blastmarketingagency.com', 'diane@blastmarketingagency.com'] WHERE client_code = 'BLAST';
UPDATE public.clients SET correspondence_emails = ARRAY['rich@leadneed.com', 'scott.coletti@gmail.com'] WHERE client_code = 'LN';
UPDATE public.clients SET correspondence_emails = ARRAY['tony@freshleydigital.com'] WHERE client_code = 'FD';
UPDATE public.clients SET correspondence_emails = ARRAY['dg@douglasgreenberg.com'] WHERE client_code = 'DG';
UPDATE public.clients SET correspondence_emails = ARRAY['sarah@thisis270m.com'] WHERE client_code = '270M';
UPDATE public.clients SET correspondence_emails = ARRAY['kshitij@mindspaceoutsourcing.com', 'bdm@mindspaceoutsourcing.com'] WHERE client_code = 'MSP';
UPDATE public.clients SET correspondence_emails = ARRAY['jeff@frontmanmarketing.com'] WHERE client_code = 'FMM';
UPDATE public.clients SET correspondence_emails = ARRAY['sbiondo@aimlogic.com'] WHERE client_code = 'AIM';
UPDATE public.clients SET correspondence_emails = ARRAY['preston@resultsdigital.io'] WHERE client_code = 'RDIG';
UPDATE public.clients SET correspondence_emails = ARRAY['yan@outify.com'] WHERE client_code = 'HB';
UPDATE public.clients SET correspondence_emails = ARRAY['yan@outify.com'] WHERE client_code = 'OUTIFY';
UPDATE public.clients SET correspondence_emails = ARRAY['kaan@librar.se'] WHERE client_code = 'LIBRAR';
UPDATE public.clients SET correspondence_emails = ARRAY['jon@oyova.com'] WHERE client_code = 'OYO';
UPDATE public.clients SET correspondence_emails = ARRAY['jeff@4spotconsulting.com'] WHERE client_code = '4Spot';
UPDATE public.clients SET correspondence_emails = ARRAY['hi@qadigitalads.com'] WHERE client_code = 'QDA';