// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onnbdclahsxoqdfgdsbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubmJkY2xhaHN4b3FkZmdkc2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDY2NjIsImV4cCI6MjA3MTA4MjY2Mn0.bVpQJ7_pmPL09RsnC_6aL9nbNylL-XgTJM-37lmDKG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});